import { useEffect, useMemo, useState } from 'react';
import { getTalentRequest, listMarketplaceCandidatesForAdmin, type AdminMarketplaceCandidateItem, type TalentRequestItem } from '../../api/admin.api';
import { createAdminProject, sendAdminProjectContract } from '../../api/projects.api';
import './admin-project-builder.css';

interface AdminProjectBuilderPageProps { requestId: string; onBack: () => void; }
const parseBudget = (value: string) => Number(value.replace(/[^0-9.]/g, '')) || 0;

export default function AdminProjectBuilderPage({ requestId, onBack }: AdminProjectBuilderPageProps) {
  const [request, setRequest] = useState<TalentRequestItem | null>(null);
  const [candidates, setCandidates] = useState<AdminMarketplaceCandidateItem[]>([]);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [scope, setScope] = useState('');
  const [budget, setBudget] = useState(''); const [currency, setCurrency] = useState<'USD' | 'INR' | 'AED'>('USD'); const [paymentTerms, setPaymentTerms] = useState('Payment due after project completion and approval.');
  const [deliverables, setDeliverables] = useState(''); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  useEffect(() => { let active = true; void Promise.all([getTalentRequest(requestId), listMarketplaceCandidatesForAdmin({ requestId, perPage: 24 })]).then(([detail, result]) => { if (!active) return; setRequest(detail); setCandidates(result.items); setTitle(detail.projectType || `${detail.companyName} project`); setDescription(detail.projectDescription || ''); setScope(detail.projectDescription || ''); setBudget(detail.budget || ''); const preselected = detail.workerId ? [detail.workerId] : (detail.shortlistedTalentProfiles ?? []).map((profile) => profile.workerId); setSelectedIds(preselected); }).catch((reason: Error) => active && setError(reason.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [requestId]);
  const selectedCandidates = useMemo(() => candidates.filter((candidate) => selectedIds.includes(candidate.workerId)), [candidates, selectedIds]);
  const toggleCandidate = (id: string) => setSelectedIds((ids) => ids.includes(id) ? ids.filter((item) => item !== id) : [...ids, id]);
  const save = async (sendNow: boolean) => { if (!title.trim() || !description.trim() || !scope.trim() || selectedIds.length === 0) { setError('Complete the project details and select at least one delivery team member.'); return; } setWorking(true); setError(''); setSuccess(''); try { const project = await createAdminProject({ talentRequestId: requestId, title, description, scope, budget: parseBudget(budget), currency, paymentTerms, deliverables: deliverables.split('\n').map((item) => item.trim()).filter(Boolean), teamMembers: selectedIds.map((workerId) => { const member = candidates.find((candidate) => candidate.workerId === workerId); return { workerId, role: member?.role || 'Delivery team member' }; }) }); if (sendNow) { await sendAdminProjectContract(project._id); setSuccess('Project contract sent to the client dashboard and email.'); } else { setSuccess('Project draft created. You can send its contract from the project list next.'); } } catch (reason) { setError((reason as Error).message); } finally { setWorking(false); } };
  if (loading) return <main className="apb-root"><div className="apb-card">Loading project builder...</div></main>;
  return <main className="apb-root"><header className="apb-header"><button type="button" onClick={onBack}>Back to request</button><div><span>Dechub Admin</span><h1>Build delivery project</h1><p>{request?.companyName || 'Client company'}: create the contract and delivery team before client acceptance.</p></div></header>{error ? <div className="apb-alert error">{error}</div> : null}{success ? <div className="apb-alert success">{success}</div> : null}<div className="apb-grid"><section className="apb-card"><h2>Project contract</h2><label>Project title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Client-facing description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Scope of work<textarea value={scope} onChange={(event) => setScope(event.target.value)} /></label><div className="apb-row"><label>Budget<input value={budget} onChange={(event) => setBudget(event.target.value)} inputMode="decimal" /></label><label>Currency<select value={currency} onChange={(event) => setCurrency(event.target.value as 'USD' | 'INR' | 'AED')}><option>USD</option><option>INR</option><option>AED</option></select></label></div><label>Payment terms<textarea value={paymentTerms} onChange={(event) => setPaymentTerms(event.target.value)} /></label><label>Deliverables, one per line<textarea value={deliverables} onChange={(event) => setDeliverables(event.target.value)} placeholder="Discovery and planning&#10;Design and development&#10;Final handover" /></label></section><section className="apb-card"><h2>Delivery team</h2><p>Each selected person receives project access and task notifications after client acceptance.</p><div className="apb-team-list">{candidates.map((candidate) => <label key={candidate.workerId} className={`apb-team-member ${selectedIds.includes(candidate.workerId) ? 'selected' : ''}`}><input type="checkbox" checked={selectedIds.includes(candidate.workerId)} onChange={() => toggleCandidate(candidate.workerId)} /><span><strong>{candidate.name}</strong><small>{candidate.role} | {candidate.location}</small></span></label>)}</div>{selectedCandidates.length === 0 ? <p className="apb-warning">Select one or more profiles for this project.</p> : <p className="apb-selected-count">{selectedCandidates.length} delivery team member{selectedCandidates.length === 1 ? '' : 's'} selected</p>}</section></div><footer className="apb-actions"><button type="button" onClick={onBack}>Cancel</button><button type="button" disabled={working} onClick={() => void save(false)}>Save draft</button><button type="button" className="primary" disabled={working} onClick={() => void save(true)}>{working ? 'Creating...' : 'Create and send contract'}</button></footer></main>;
}
