import fs from 'fs/promises';
import path from 'path';
import { env } from '../config/env';
import type { IContract } from '../models/Contract';

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'contract';
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrapText(text: string, maxChars = 88): string[] {
  const normalized = text.replace(/\s+/g, ' ').trim();
  if (!normalized) return [''];

  const words = normalized.split(' ');
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= maxChars) {
      current = next;
      continue;
    }
    if (current) {
      lines.push(current);
      current = word;
      continue;
    }
    lines.push(word.slice(0, maxChars));
    current = word.slice(maxChars);
  }

  if (current) lines.push(current);
  return lines;
}

function formatDate(value: Date | null | undefined): string {
  if (!value) return '-';
  return new Date(value).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function buildPdfBuffer(lines: string[]): Buffer {
  const pageHeight = 792;
  const left = 54;
  const top = 740;
  const lineHeight = 16;
  const contentLines = ['BT', '/F1 11 Tf'];

  lines.forEach((line, index) => {
    const y = top - (index * lineHeight);
    contentLines.push(`1 0 0 1 ${left} ${y} Tm (${escapePdfText(line)}) Tj`);
  });

  contentLines.push('ET');
  const stream = contentLines.join('\n');

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj',
    `3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 ${pageHeight}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj`,
    '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
    `5 0 obj\n<< /Length ${Buffer.byteLength(stream, 'utf8')} >>\nstream\n${stream}\nendstream\nendobj`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];

  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${object}\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
}

function buildContractLines(contract: IContract): string[] {
  const typeLabel = contract.contractType === 'full_time_employee'
    ? 'Employment Agreement'
    : 'Independent Contractor Agreement';
  const statusLabel = contract.status.replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
  const signatureSummary = [
    `Contractor signature: ${contract.workerSigned ? `Signed on ${formatDate(contract.workerSignedAt)}` : 'Pending'}`,
    `Company signature: ${contract.companySigned ? `Signed on ${formatDate(contract.companySignedAt)}` : 'Pending'}`,
  ];

  return [
    ...wrapText(typeLabel, 70),
    '',
    ...wrapText(`Company: ${contract.companyName}`),
    ...wrapText(`Worker: ${contract.workerName}`),
    ...wrapText(`Role: ${contract.roleTitle}`),
    `Track: ${contract.track === 'track_2_us' ? 'Track 2 - US' : 'Track 1 - India'}`,
    `Status: ${statusLabel}`,
    ...wrapText(`Pay rate: ${contract.payCurrency} ${contract.payRate.toLocaleString()} per ${contract.payFrequency}`),
    `Start date: ${formatDate(contract.startDate)}`,
    `End date: ${contract.endDate ? formatDate(contract.endDate) : 'Open-ended'}`,
    `Notice period: ${contract.noticePeriodDays} days`,
    '',
    'Scope of work:',
    ...wrapText(contract.scopeOfWork || 'Not provided.'),
    '',
    'Key terms:',
    ...wrapText('The contractor is engaged as an independent service provider unless otherwise stated. Confidentiality obligations apply throughout the engagement. Intellectual property created for the engagement belongs to the company unless the contract says otherwise.'),
    '',
    'Signature status:',
    ...signatureSummary.flatMap((line) => wrapText(line)),
    '',
    ...wrapText(`Generated by Dechub on ${formatDate(new Date())}.`),
  ];
}

export function getContractPdfFilename(contract: Pick<IContract, 'companyName' | 'workerName'>): string {
  return `${slugify(contract.companyName)}-${slugify(contract.workerName)}-contract.pdf`;
}

export async function syncContractPdf(
  contract: IContract,
  serverBaseUrl: string,
  options: { force?: boolean } = {},
): Promise<string> {
  if (contract.pdfUrl && !options.force) {
    return contract.pdfUrl;
  }

  const uploadsDir = path.resolve(env.UPLOAD_DIR);
  const contractsDir = path.join(uploadsDir, 'contracts');
  await fs.mkdir(contractsDir, { recursive: true });

  const filename = `${contract._id}-${getContractPdfFilename(contract)}`;
  const filePath = path.join(contractsDir, filename);
  const buffer = buildPdfBuffer(buildContractLines(contract));
  await fs.writeFile(filePath, buffer);

  contract.pdfUrl = `${serverBaseUrl.replace(/\/$/, '')}/uploads/contracts/${filename}`;
  contract.pdfGeneratedAt = new Date();
  await contract.save();

  return contract.pdfUrl;
}
